name: Userspace Build
on:
  workflow_dispatch:
  push:
    paths:
      - 'keyboards/**'
      - 'keymaps/*'
      - '.github/workflows/*'
      - '*.def'
      - '*.c'
      - '*.h'


jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    env:
      QMK_USER: users/${{ github.actor }}
      USER_KEYMAPS: users/${{ github.actor }}/keymaps

    # by default, checks out to github.workspace
    # github.workspace will also be qmk_firmware root
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3.5.3
      with:
        repository: qmk/qmk_firmware
        ref: master
        submodules: true

    # path is relative to github.workspace
    - name: Checkout userspace
      uses: actions/checkout@v3.5.3
      with:
        path: ${{ env.QMK_USER }}
        persist-credentials: false

    - name: Setup safe directory
      run: git config --global --add safe.directory '*'

    - name: Copy users/keyboards/* to keyboards/*
      run: rsync -av ${{ env.QMK_USER }}/keyboards/ keyboards/

    - name: Compile
      run: for kb in $(ls ${{ env.USER_KEYMAPS }}/*.json); do qmk compile -j 3 $kb -km ${{ github.actor }}; done

    - name: Archive firmware
      uses: actions/upload-artifact@v3.1.2
      with:
        retention-days: 60
        name: qmk_firmware
        path: |
          *.hex
          *.bin
          *.uf2
